version: '3'
services: 
    dockerapp:
        build: ./dockerapp/composepy4/
        ports: 
            - "5000:5000"
        depends_on: 
            - redis
        networks: 
            - my_net
    redis:
        image: redis
        networks: 
            - my_net
networks: 
    my_net: 
        driver: bridge